### ISSUE TITLE
 Bad POM in Maven Central

### ISSUE THREAD

**Issue by stefanbirkner** [hazendaz/base-parent#252]
I have an Artifactory that connects to Maven Central. Unfortunately it cannot download version 28 of the base-parent because it considers this POM to be broken. The cause for it is the `project` start tag

    <project
      child.project.url.inherit.append.path="false"
      xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

In version 27 the start tag was simply 

    <project xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

like usual. The additional attribute was introduced in b96c4a251e60f42453b62fd9025ad22af3d3f4fe.

**Comment by stefanbirkner** [comment]
The POM is valid. It seems to be Artifactory's fault that it cannot read the POM.

**Comment by hazendaz** [comment]
Seems they fixed in 6.18, are you ok with their fix or still need removed?  If you still need removed, please reopen this and let me know.  The attempt here in usage was to fix site page generate on downstream projects which didn't work like maven stated it would, along with issues persistent with validation still not working in some IDEs last I checked.

**Comment by stefanbirkner** [comment]
Since it is an Artifactory but I'm fine with keeping it like it is. Thanks for explaining the reason for using this attributes.
